In [36]:
#Esta celda da formato al texto del Notebook.
from IPython.core.display import HTML

HTML("""
<style>
h1 {
    text-align: center;
}
</style>
""")

<h1>Matriz Ampliada con ceros</h1>

In [64]:
for var in globals().copy():
    if not var.startswith("_"):
        del globals()[var]
import numpy as np

img = np.array([
    [[1,1,1],[1,1,1],[1,1,1]],
    [[1,1,1],[1,1,1],[1,1,1]],
    [[1,1,1],[1,1,1],[1,1,1]]
])
#print(img.shape,"\n")
filaDeCeros =np.zeros((1,img.shape[1],img.shape[2]), dtype = img.dtype)
#print(filaDeCeros.shape)
ampliada = np.insert(img, np.s_[::1], filaDeCeros, axis=0)
#print(ampliada.shape,"\n")
ampliada = np.vstack((ampliada, filaDeCeros))
#print(ampliada.shape,"\n")
columnaDeCeros = np.zeros((ampliada.shape[0],1,img.shape[2]), dtype = ampliada.dtype)
ampliada = np.insert(ampliada,np.s_[0::1],columnaDeCeros, axis = 1)
#print(ampliada.shape,"\n")
ampliada = np.hstack((ampliada,columnaDeCeros))
print(ampliada.shape,"\n")
print(ampliada,"\n")

(7, 7, 3) 

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [1 1 1]
  [0 0 0]
  [1 1 1]
  [0 0 0]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [1 1 1]
  [0 0 0]
  [1 1 1]
  [0 0 0]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [1 1 1]
  [0 0 0]
  [1 1 1]
  [0 0 0]
  [1 1 1]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]] 



<h1>Convolución con máscara</h1>

In [67]:
mascara_conv = np.array([[0.25,0.5 ,0.25],[0.5,1 ,0.5],[0.25,0.5 ,0.25]])
region_conv = ampliada[1:-1,1:-1,:]
print(mascara_conv.shape)
print(region_conv.shape)
new_img = np.multiply(ampliada[1:,1:,1],mascara_conv)

(3, 3)
(5, 5, 3)


ValueError: operands could not be broadcast together with shapes (6,6) (3,3) 