In [17]:
#Esta celda da formato al texto del Notebook.
from IPython.core.display import HTML

HTML("""
<style>
h1 {
    text-align: center;
}
</style>
""")

<h1>Matriz Ampliada con ceros</h1>

In [62]:
for var in globals().copy():
    if not var.startswith("_"):
        del globals()[var]
import numpy as np

img = np.array([
    [[1],[2],[3]],
    [[4],[5],[6]],
    [[7],[8],[9]]
])
#print(img.shape,"\n")
filaDeCeros =np.zeros((1,img.shape[1],img.shape[2]), dtype = int)
#print(filaDeCeros.shape)
ampliada = np.insert(img, np.s_[::1], filaDeCeros, axis=0)
#print(ampliada.shape,"\n")
ampliada = np.vstack((ampliada, filaDeCeros))
#print(ampliada.shape,"\n")
columnaDeCeros = np.zeros((ampliada.shape[0],1,img.shape[2]), dtype = int)
ampliada = np.insert(ampliada,np.s_[0::1],columnaDeCeros, axis = 1)
#print(ampliada.shape,"\n")
ampliada = np.hstack((ampliada,columnaDeCeros))
print(ampliada.shape,"\n")
#print(ampliada,"\n")


(7, 7, 1) 



<h1>Convolución con máscara</h1>

In [65]:
mascara_conv = np.array([[0.25,0.5 ,0.25],[0.5,1 ,0.5],[0.25,0.5 ,0.25]])
region_conv = ampliada[1:-1,1:-1,:]
print(mascara_conv.shape)
print(region_conv.shape)
print("Región de convolución","\n \n",region_conv, "\n")
resultado_conv = np.zeros_like(ampliada)
for i, j in np.ndindex(region_conv.shape[:2]):
    elemento = region_conv[i, j]
    print("Elemento en la posición ({},{}) es: {}".format(i, j, elemento))
    print("elementos adyacentes")
    for elemento in ampliada[i:i+3,j:j+3]:
        print(elemento)

        
   


(3, 3)
(5, 5, 1)
Región de convolución 
 
 [[[1]
  [0]
  [2]
  [0]
  [3]]

 [[0]
  [0]
  [0]
  [0]
  [0]]

 [[4]
  [0]
  [5]
  [0]
  [6]]

 [[0]
  [0]
  [0]
  [0]
  [0]]

 [[7]
  [0]
  [8]
  [0]
  [9]]] 

Elemento en la posición (0,0) es: [1]
elementos adyacentes
[[0]
 [0]
 [0]]
[[0]
 [1]
 [0]]
[[0]
 [0]
 [0]]
Elemento en la posición (0,1) es: [0]
elementos adyacentes
[[0]
 [0]
 [0]]
[[1]
 [0]
 [2]]
[[0]
 [0]
 [0]]
Elemento en la posición (0,2) es: [2]
elementos adyacentes
[[0]
 [0]
 [0]]
[[0]
 [2]
 [0]]
[[0]
 [0]
 [0]]
Elemento en la posición (0,3) es: [0]
elementos adyacentes
[[0]
 [0]
 [0]]
[[2]
 [0]
 [3]]
[[0]
 [0]
 [0]]
Elemento en la posición (0,4) es: [3]
elementos adyacentes
[[0]
 [0]
 [0]]
[[0]
 [3]
 [0]]
[[0]
 [0]
 [0]]
Elemento en la posición (1,0) es: [0]
elementos adyacentes
[[0]
 [1]
 [0]]
[[0]
 [0]
 [0]]
[[0]
 [4]
 [0]]
Elemento en la posición (1,1) es: [0]
elementos adyacentes
[[1]
 [0]
 [2]]
[[0]
 [0]
 [0]]
[[4]
 [0]
 [5]]
Elemento en la posición (1,2) es: [0]
elemento