In [2]:
#Esta celda da formato al texto del Notebook.
from IPython.core.display import HTML

HTML("""
<style>
h1 {
    text-align: center;
}
</style>
""")

<h1>Matriz Ampliada con ceros</h1>

In [46]:
for var in globals().copy():
    if not var.startswith("_"):
        del globals()[var]
import numpy as np

img = np.array([
    [[1],[2],[3]],
    [[4],[5],[6]],
    [[7],[8],[9]]
])
#print(img.shape,"\n")
filaDeCeros =np.zeros((1,img.shape[1],img.shape[2]), dtype = int)
#print(filaDeCeros.shape)
ampliada = np.insert(img, np.s_[::1], filaDeCeros, axis=0)
#print(ampliada.shape,"\n")
ampliada = np.vstack((ampliada, filaDeCeros))
#print(ampliada.shape,"\n")
columnaDeCeros = np.zeros((ampliada.shape[0],1,img.shape[2]), dtype = int)
ampliada = np.insert(ampliada,np.s_[0::1],columnaDeCeros, axis = 1)
#print(ampliada.shape,"\n")
ampliada = np.hstack((ampliada,columnaDeCeros))
print(ampliada.shape,"\n")
#print(ampliada,"\n")


(7, 7, 1) 



<h1>Convolución con máscara</h1>

In [51]:
mascara_conv = np.array([[0.25,0.5 ,0.25],[0.5,1 ,0.5],[0.25,0.5 ,0.25]])
region_conv = ampliada[1:-1,1:-1,:]
#print(mascara_conv.shape)
#print(region_conv.shape)
print(img.shape)
#print("Región de convolución","\n \n",region_conv, "\n")
resultado_conv = np.zeros_like(img)
sum = 0
for i, j in np.ndindex(region_conv.shape[:2]):
    print((i,j))
    elemento = region_conv[i, j]
    #print("Elemento en la posición ({},{}) es: {}".format(i, j, elemento))
    #print("elementos adyacentes")
    #print(ampliada[i:i+3,j:j+3])
    for indice, valor in np.ndenumerate(ampliada[i:i+3,j:j+3]):
        print("indice: ",indice, "valor: ",valor)
        #print("valor mascara convolución: " ,mascara_conv[indice[0],indice[1]])
        #print(valor*mascara_conv[indice[0],indice[1]])
        sum += valor*mascara_conv[indice[0],indice[1]]
    print("sum : ", sum)
    resultado_conv[i, j] = sum # J SOBREPASA 3, RESOLVER
    print("resultado_conv: ", resultado_conv)
    sum = 0
    """for elemento in ampliada[i:i+3,j:j+3]:
        print("*",elemento,"*")
        for index,k in enumerate(elemento):
            print(index,"**",k,"**")"""
            

        
   


(3, 3, 1)
(0, 0)
indice:  (0, 0, 0) valor:  0
indice:  (0, 1, 0) valor:  0
indice:  (0, 2, 0) valor:  0
indice:  (1, 0, 0) valor:  0
indice:  (1, 1, 0) valor:  1
indice:  (1, 2, 0) valor:  0
indice:  (2, 0, 0) valor:  0
indice:  (2, 1, 0) valor:  0
indice:  (2, 2, 0) valor:  0
sum :  1.0
resultado_conv:  [[[1]
  [0]
  [0]]

 [[0]
  [0]
  [0]]

 [[0]
  [0]
  [0]]]
(0, 1)
indice:  (0, 0, 0) valor:  0
indice:  (0, 1, 0) valor:  0
indice:  (0, 2, 0) valor:  0
indice:  (1, 0, 0) valor:  1
indice:  (1, 1, 0) valor:  0
indice:  (1, 2, 0) valor:  2
indice:  (2, 0, 0) valor:  0
indice:  (2, 1, 0) valor:  0
indice:  (2, 2, 0) valor:  0
sum :  1.5
resultado_conv:  [[[1]
  [1]
  [0]]

 [[0]
  [0]
  [0]]

 [[0]
  [0]
  [0]]]
(0, 2)
indice:  (0, 0, 0) valor:  0
indice:  (0, 1, 0) valor:  0
indice:  (0, 2, 0) valor:  0
indice:  (1, 0, 0) valor:  0
indice:  (1, 1, 0) valor:  2
indice:  (1, 2, 0) valor:  0
indice:  (2, 0, 0) valor:  0
indice:  (2, 1, 0) valor:  0
indice:  (2, 2, 0) valor:  0
sum :  2.0

IndexError: index 3 is out of bounds for axis 1 with size 3